spring:
  url:
    base: http://localhost:8080
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: